services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
     - '3000:3000'
    volumes:
     - /home/sierra/csv:/var/lib/grafana/csv
     - /home/sierra/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
     - grafana-data:/var/lib/grafana
    environment:
     - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
    restart: unless-stopped

volumes:
  grafana-data:
